version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m5j1b6u0
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t zinc:latest .
      - docker tag zinc:latest public.ecr.aws/m5j1b6u0/zinc:latest
      - docker tag zinc:latest public.ecr.aws/m5j1b6u0/zinc:v$CODEBUILD_BUILD_NUMBER      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/m5j1b6u0/zinc:latest
      - docker push public.ecr.aws/m5j1b6u0/zinc:v$CODEBUILD_BUILD_NUMBER

      